name: Performance Test

on:
  push:
    branches: [ "main" ]

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install k6

      - name: Run Performance Test
        run: k6 run test.js

